### PR TITLE
Adds Yarn, uses ESLint in place of JSHint/JSCS

### LINKED ISSUE #3: Consider using yarn
For faster CI builds and consistency that yarn.lock provides

### PR DESCRIPTION
**Pull request by camsjams**
No new features, mostly just maintenance, and addresses #3 

- Adds Yarn
- uses ESLint in place of JSHint/JSCS
- Reformatted according to new ESLint rules
- Updated constructor letter-casing for Promise Factory

### CODE REVIEW

**Comment by oshalygin** [comment]
Looks good but can we squash the commits?

**Comment by oshalygin** [comment]
Also, tab vs spaces?  As long as you're sure :)

**Comment by camsjams** [comment]
Well I usually do the PR from feature branch to develop, but Circle was acting up so had to merge into develop. Once I finish the release for this it will be a single squashed commit into master.

**Comment by camsjams** [comment]
see: https://github.com/camsjams/node-treasury/commit/250fc849ad25814e7650b1a37e836b2147df14ec

**Pull request closed without merging**
